name: Disabler
version: "1.0"
author: ogiwara
api: ["1.0.0"]
main: me.ogiwara.Disabler.Disabler
description: Disable spesific plugin with command.
commands:
 disable:
  aliases: [dis]
  description: "Disable command."
  usage: "/disable <name> to diable specific plugin.(aliases /dis)"
  permission: "disable.command"
 permissions:
  disable.command:
   default: op